print("Здравствуйте, вы проходите анкету")
first_name = input("Введите ваше имя:")
last_name = input("Введите вашу фамилию:")
date_year= input("Введите ваш год рождения:")
email = input("email:")
course= input("Нравится ли вам курс?")
vopros= input("Что вы ожидаете в дальнейших занятиях?")
poka= ("Вы заполнили такие данные:")
full_name = first_name + ' ' + last_name
age= 2023 - int(date_year)
print(poka)
print("full name:", full_name)
print("age:", age)
print("email:", email)
print("Нравится ли вам курс?", course)
print("Что вы ожидаете в дальнейших занятиях?", vopros)
